substitutions:
  devicename: spare_bulb_cwww
  upper_devicename: Spare Bulb CWWW

esphome:
  name: $devicename
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${friendly_name}
    password: "51Uv8rKokvrP"

captive_portal:

logger:

ota:

api:
  #disables automatic reboot, will need to physically switch on and off again
  reboot_timeout: 0s

sensor:
 #signal wifi
  - platform: wifi_signal
    name: ${devicename}_signal
    update_interval: 300s

#ip address
#text_sensor:
#  - platform: wifi_info
#    ip_address:
#      name: ${devicename}_wifi

output:
  - platform: esp8266_pwm
    id: output_warm_white
    pin: GPIO4
  - platform: esp8266_pwm
    id: output_cold_white
    pin: GPIO5

light:
  - platform: cwww
    name: $upper_devicename
    id: light_cwww
    cold_white: output_cold_white
    warm_white: output_warm_white
    cold_white_color_temperature: 5000 K
    warm_white_color_temperature: 2000 K

    # Ensure the light turns on by default if the physical switch is actuated.
    restore_mode: ALWAYS_ON