# ##################################
# Zemismart BCM500DS-TYW Automated Curtains with BH1750 Lux
# ##################################
# For flashing the software:
# TYWE1S U0TX (GPIO1) --> USB Tool 'RXD'
# TYWE1S U0RX (GPIO3) --> USB Tool 'TXD'
# TYWE1S IO0 --> GND (or just hold reset button? Not sure if wired)
# TYWE1S GND --> USB Tool 'GND'
# TYWE1S 3V3 --> USB Tool '3V'

# ##################################
# For Programming the pins:
# TYWE1S GPIO15 (U1TX) = TX for the Tuya Module, already connected on circuit board
# TYWE1S GPIO13 (U1RX) = RX for the Tuya Module, already connected on circuit board
#
# TYWE1S 'GPI05' --> BH-1750 'SCL'
# TYWE1S 'GPIO4' --> BH-1750 'SDA'
# TYWE1S '3V' --> BH-1750 'VCC'
# TYWE1S 'G' --> BH-1750 'GND'
# ##################################
# https://community.home-assistant.io/t/tuya-curtain-motor-custom-component-with-set-position-and-realtime-feedback/185537/35
# https://tasmota.github.io/docs/Pinouts/
# https://www.iot-kit.nl/docs/sensor-bh1750/
# ##################################
substitutions:
  device_name: west-window
  friendly_name: West Window

esphome:
  name: ${device_name}
  platform: ESP8266
  board: esp01_1m
  includes:
    - custom_components/zemismart_curtain.h

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: west_window.local

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${friendly_name}
    password: "51Uv8rKokvrP"

captive_portal:

logger:
  baud_rate: 0

ota:

api:

# The Tuya UART communication initiation
uart:
  - id: com_1
    rx_pin: GPIO13
    tx_pin: GPIO15
    baud_rate: 9600

# # The lux sensor broke, we will use the one in the bedroom window instead. Disable the i2c and lux sensor in this YAML for efficiency.
# # The BH1750 sensor is an I2C sensor, so first prepare the controller to talk to I2C sensors
# i2c:
#   sda: GPIO4
#   scl: GPIO5
#   scan: False

globals:
  - id: cover_open
    type: bool
    restore_value: true
    initial_value: "false"
  - id: cover_reversed
    type: bool
    restore_value: true
    initial_value: "false"
  - id: cover_position
    type: float
    restore_value: true
    initial_value: "0"

cover:
  - platform: custom
    lambda: |-
      auto curtain = new CustomCurtain();
      App.register_component(curtain);
      return {curtain};
    covers:
      - name: ${friendly_name}
        device_class: curtain

custom_component:
  - lambda: |-
      return { new CustomAPI() };

sensor:
  #wifi signal
  - platform: wifi_signal
    name: ${device_name}_signal
    update_interval: 300s
    filters:
      - sliding_window_moving_average:
          window_size: 12
          send_every: 12
      - delta: 1

  # # The lux sensor broke, we will use the one in the bedroom window instead. Disable the i2c and lux sensor in this YAML for efficiency.
  # # The BH1750 sensor by default uses I2C address 0X23
  # - platform: bh1750
  #   name: ${friendly_name} Brightness
  #   address: 0x23
  #   update_interval: 10s
  #   filters:
  #     - sliding_window_moving_average:
  #         window_size: 12
  #         send_every: 6
  #     - delta: 5